# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Piece')),
            ],
        ),
    ]
