# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('likes_number', models.IntegerField()),
                ('image', models.CharField(max_length=256)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Artist')),
            ],
        ),
    ]
