# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161119_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='title',
            field=models.CharField(default='prueba', max_length=256),
            preserve_default=False,
        ),
    ]
