# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_newsfeed_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='image',
            field=models.CharField(max_length=600),
        ),
    ]
