# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161120_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
