# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161120_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiecePlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='artist_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pieceplaylist',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Piece'),
        ),
        migrations.AddField(
            model_name='pieceplaylist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlayList'),
        ),
    ]
